### ISSUE TITLE
Deploy Bundle to pratikgarala.github.io

### ISSUE THREAD

**Issue by ron4ex** [pratikgarala/pratikgarala.github.io#1]
- [x] **Appropriate naming conventions:** The `src` directory currently holds the bundled code which is not how it should be. `src` should generally contain the Source Code while `dist`/`build` should contain files to deploy. So _current_ `dev` :point_right: `src` & _current_ `src` :point_right: `build`
- [x] **Deploy:** Contents of `build` folder to pratikgarala.github.io

**Comment by pratikgarala** [comment]
Names has been changed from src 👉 build and dev 👉 src.

**Comment by ron4ex** [comment]
Looks like Github doesn't allow publishing to _User Pages_ from a sub-folder :point_down:

![screenshot from 2016-12-24 17 16 52](https://cloud.githubusercontent.com/assets/5601641/21466911/f8c4ca62-c9fe-11e6-86c6-e5c59181d10d.png)


For now, the site is live at https://pratikgarala.github.io/build/ instead of https://pratikgarala.github.io/ So lets go ahead with that.
